#!/bin/bash
### BEGIN INIT INFO
# Provides:          ntrs
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       "Name Tag Response Server"
### END INIT INFO

sudo python /opt/ntrs/ntrs.py "$@"
